### PR TITLE
Fixes #9 Bridge error when no file is selected

### LINKED ISSUE #9: Bridge error when no file is selected
The bridge throws an error when a file element is posted without selecting a file.

    $_FILES
    Array ( [file] => Array ( [name] => [type] => [tmp_name] => [error] => 4 [size] => 0 ) ) 
    error = 4 = UPLOAD_ERR_NO_FILE

    $symfonyRequest->files->all()
    Array ( [file] =>)

    Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory::getFiles()
    Catchable Fatal Error: Argument 1 passed to    
    Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory::getFiles() must be of the type array, 
    null given

The problem is that the Symfony request object contains a null for file elements if no file was selected.  One could argue that it should return an UploadedFile object with an error code of UPLOAD_ERR_NO_FILE (4) but obviously this is not something that would be considered for S2.7.  Don't know if it has been discussed for 3.x.

However, the PSR7 spec seems clear:

    interface ServerRequestInterface extends RequestInterface
    public function getUploadedFiles();
    * This method returns upload metadata in a normalized tree, with each leaf
    * an instance of Psr\Http\Message\UploadedFileInterface.

So for PSR7 we should return metadata even if a file was not actually uploaded.  Which is exactly what Zend\Diactoros\ServerRequestFactory::fromGlobals() does.

It's easy enough to update the bridge to match the Zend PSR7 behavior when no file has been selected.  I'll be glad to submit a pull request.  Just wanted to make sure that it would be accepted.

### PR DESCRIPTION
**Pull request by Danielss89**
Q	A
Bug fix?	yes
New feature?	no
BC breaks?	no
Deprecations?	no
Tests pass?	yes
Fixed tickets	#9
License	MIT
Doc PR

### CODE REVIEW

File: Factory/HttpFoundationFactory.php [hunk 1]
```diff
@@ -80,10 +80,14 @@ private function getFiles(array $uploadedFiles)
      */
     private function createUploadedFile(UploadedFileInterface $psrUploadedFile)
     {
-        $temporaryPath = $this->getTemporaryPath();
-        $psrUploadedFile->moveTo($temporaryPath);
+        $temporaryPath = '';
+        $clientFileName = null;
```
Comment (Tobion) [inline Factory/HttpFoundationFactory.php]: you could set this to `''`. below there is a check against null which only need to trigger if `$psrUploadedFile->getClientFilename()` returns null.

File: Tests/Factory/DiactorosFactoryTest.php [hunk 2]
```diff
@@ -161,4 +161,33 @@ public function testCreateResponseFromBinaryFile()
 
         $this->assertEquals('Binary', $psrResponse->getBody()->__toString());
     }
+
+    public function testUploadErrNoFile()
+    {
+        $file = new UploadedFile('', null, null, 0, UPLOAD_ERR_NO_FILE, true);
```
Comment (Tobion) [inline Tests/Factory/DiactorosFactoryTest.php]: the second parameter should not be null

**Comment by Tobion** [comment]
Please squash commits per author (1 commit per author).

File: Tests/Factory/DiactorosFactoryTest.php [hunk 3]
```diff
@@ -161,4 +161,33 @@ public function testCreateResponseFromBinaryFile()
 
         $this->assertEquals('Binary', $psrResponse->getBody()->__toString());
     }
+
+    public function testUploadErrNoFile()
+    {
+        $file = new UploadedFile('', '', null, 0, UPLOAD_ERR_NO_FILE, true);
+        $this->assertEquals(0, $file->getSize());
+        $this->assertEquals(UPLOAD_ERR_NO_FILE, $file->getError());
+        $this->assertFalse($file->getSize());
```
Comment (xabbuh) [inline Tests/Factory/DiactorosFactoryTest.php]: There should be [a third argument](https://github.com/symfony/psr-http-message-bridge/pull/10#discussion_r58193053) like this:

```php
$this->assertFalse($file->getSize(), 'SplFile::getSize() returns false on error');
```

Comment (hexus) [inline Tests/Factory/DiactorosFactoryTest.php]: Don't you mean a second argument to `assertFalse`? It would be a third argument for `assertEquals`, but the comment you linked to erroneously mentioned `assertFalse`.

Assert false [doesn't take a third argument](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertFalse).

**Comment by weaverryan** [comment]
It looks like all the comments from #10 have been addressed here. Does anyone else have any issues, or can we merge this?

**Comment by fabpot** [comment]
Thank you @Danielss89.
